# Generated by Django 3.0.7 on 2020-06-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_auto_20200629_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_timber',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='tiles',
        ),
    ]
